# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy all files into the container
COPY . .

# Change working directory to the everything server directory
WORKDIR /app/src/everything

# Install dependencies and build the project
RUN npm install --ignore-scripts && npm run build

# Expose port if necessary (optional)
# EXPOSE 3000

# Start the MCP server
CMD [ "node", "dist/index.js" ]
